### ISSUE TITLE
About iFormatTool extension

### ISSUE THREAD

**Issue by mengkunsoft** [maicong/about#3]
大佬，你的 iFormatTool 用不了了……有更新的计划吗
一直在用，目前找不到顺手替代方案 T_T
![2](https://user-images.githubusercontent.com/16880885/177901027-e14de7f1-541f-48ec-b4ae-b601e074c878.png)
![1](https://user-images.githubusercontent.com/16880885/177901037-61249206-f458-4e68-8a75-a9f52d6dd371.png)

**Comment by maicong** [comment]
以普遍理论性而言，这个作者不会去维护之前的插件了。

**Comment by mengkunsoft** [comment]
太可惜了，这么好的插件 😭
感谢这个作者一直以来的付出 ❤❤❤
